export const baseUrl = 'https://api.wetrue.io'
export const nodeUrl = 'https://node.aechina.io/'
//export const baseUrl = 'https://liushao.cc:1817'
//export const nodeUrl = 'https://liushao.cc:5013/'
export const version = '2.3.5'
export const aeknow = 'https://www.aeknow.org/'