export const baseUrl = 'https://api.wetrue.io'
export const nodeUrl = 'https://node.aechina.io/'
export const aeknow = 'https://www.aeknow.org/'
export const version = '2.4.3'
export const source = 'WeTrue App'